module.exports = [
    {
      captainName: "Jeanne de Clisson",
      yearBorn: 1300,
      yearsAlive: 59,
      culture: "French",
      timePeriod: "14th century",
      is_bornIntoMoney: true,
      title: "Justice turned Vengenance, Defy Societal Norms",
      whyPiracy: "To avenge her husband who was executed by the French king for treason",
      somethingILoveAboutHer: "Her mission was to let everyone know WHY she betrayed her country so she let at least one sailor live to carry her message.",
      knownFor: "13 years of havoc as the 'Lioness of Brittany' -- She painted sails black and red titled: My Revenge",
      storyEnds: "Supposedly, King Charles VI of France offered her a pardon and the return of her husband’s lands in 1380. She remarried and lived as a wealthy and respected noblewoman on her estates in Brittany."
    },
    {
      captainName: "Sayyida al Hurra",
      yearBorn: 1485,
      yearsAlive: 75,
      culture: "Morrocan",
      timePeriod: "16th century",
      is_bornIntoMoney: true,
      title: "Sovereign, bows to no superior authority",
      whyPiracy: "Family's forced exile from Grenada; and defense of her coastal town",
      somethingILoveAboutHer: "Her marriage was the first recorded instance of a Morroccan king marrying outside of his capital. She wanted to show her people that the marriage wouldn't be distracting to her role as the Governor.",
      knownFor: "Being the Governor of Tétouan",
      storyEnds: "She was stripped of her power and property by her son-in-law; retired to Chefchaouen"
    },
    {
      captainName: "Lady Killigrew (Mary Wolverston)",
      yearBorn: 1525,
      yearsAlive: 62,
      culture: "English",
      timePeriod: "16th century",
      is_bornIntoMoney: true,
      title: "I Do What I Want, I'm Good; on the Hood",
      whyPiracy: "It was in her blood. Father was a 'gentleman pirate' and husband was appointed to suppress privacy via Queen Elizabet I.",
      somethingILoveAboutHer: "Double Life! She just wanted to be wild outside!",
      knownFor: "Being adventurous, dangerous, and cunning.  Redesigned her their castle to hide stolen goods, and cut deals with smugglers.",
      storyEnds: "She was tried, convicted, and sentenced to death. Two of her accomplices were executed, but she received a commutation from Queen Elizabeth, and was later released from prison after her son doled out lavish bribes."
    },
    {
      captainName: "Gráinne Ní Mháille (Grace O'Malley)",
      yearBorn: 1530,
      yearsAlive: 73,
      culture: "Irish",
      timePeriod: "16th century",
      is_bornIntoMoney: true,
      title: "Powerful by land and by sea",
      whyPiracy: "Despite having a brother, upon the death of her father, Eoghan Dubhdara, a Gaelic chieftain, she took over active leadership of the “Ó Máille” lordship by land and sea to protect the west Ireland region from the growing threat of the English crown.",
      somethingILoveAboutHer: "She was said to have just given birth and had to storm up the deck to conquer enemy that were overtaking her men. She even refused to bow to the Queen, and was able to live to tell it.  She was a BOSS.",
      knownFor: "'The Pirate Queen' the greatest female 'pirate' of the world ever. Known for her strategic thinking, navigated politics",
      storyEnds: "Her life has inspired many musicians, novelists, and playwrights to create works based on her life and adventures and she has been used as a personification of Ireland. There’s an O’Malley joke that the only man in the O’Malley family was a woman."
    },
    {
      captainName: "Jeanne Baret",
      yearBorn: 1740,
      yearsAlive: 67,
      culture: "French",
      timePeriod: "18th century",
      is_bornIntoMoney: false,
      title: "In disguise...they think I'm some...little do they know",
      whyPiracy: "She was a botanist, and her lover, Philibert Commerson, was selected to be part of a round-the-world expedition. She disguised herself as a young man, and at dockside before departing for the expedition, offered her services as Commerson’s assistant",
      somethingILoveAboutHer: "Women were prohibited on French navy ships, but they formulated a creative plan that kept Commerson protected, to this day.  She took that risk/opportunity, in the name of Love.  Full of surprises, she left her child in her early years, but was a devoted aunt in her later years... it's a real life movie ya'll!",
      knownFor: "Pre-relationship, she grew up around traditional folk and was known as a 'herb woman' in her community. Her work collecting new species during the voyage was an early contribution to Taxonomy (science of categorizing living things into family groups)",
      storyEnds: "She was granted property in her own right in Mauritius and was running her own lucrative bar. Her second husband brought 5000 livres to the marriage while Jeanne brought a house, slaves, furniture, clothes, jewelery and a small fortune of 19,500 livres. (she was wealthy enough to require a pre-nuptial contract.)"
    },
    {
      captainName: "Zheng Yi Sao (Ching Shih)",
      yearBorn: 1775,
      yearsAlive: 69,
      culture: "Chinese",
      timePeriod: "19th century",
      is_bornIntoMoney: false,
      title: "Most Successful, Most Feared",
      whyPiracy: "Death of husband, notorious pirate Zhengy Yi, she stepped into over 70,000+ men, history's largest pirate fleet",
      somethingILoveAboutHer: "Her rules protected women: Rape punishable by death, women of raided villages must not be harmed, must marry female prisoner and treat her well to bed her.",
      knownFor: "Her strict code of conduct, which included rules against rape, mistreatment of prisoners, desertion, unauthorized attacks, and distributing loot unequally.",
      storyEnds: "For nearly a decade, she led the largest and most successful pirate fleet in history. She retired with her dignity, all her ill-gotten loot, and owned a gambling house."
    },
    {
      captainName: "Krystyna Chojnowska-Liskiewicz",
      yearBorn: 1936,
      yearsAlive: 84,
      culture: "Polish",
      timePeriod: "20th century",
      is_bornIntoMoney: false,
      title: "Do it like it's never been Done before",
      whyPiracy: "Not piracy per se, but she was a naval engineer and sailor.  She's the first woman to sail around the world solo. *Note* Naomi James completed the circumnavigation in 272 days, yet arrived 2 months after Krystyna, who took 401 days.",
      somethingILoveAboutHer: "Storms, equipment failures, and even a collision with a whale that damaged her boat’s hull. She persevered and completed the voyage in just over a year.",
      knownFor: "Sailing clubs all over Poland experienced a real siege, everyone wanted to be like Krystyna Chojnowska-Liskiewicz.",
      storyEnds: "She elevated the position of women in the sailing, sterotypically male world."
    },
  ];